apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: db-secret
  namespace: default
spec:
  encryptedData:
    password: AgBi1QOVxjfSeq53J5sBMxxvmBlhjJDo9j8rMWzknqmKHvQFFVYLTHXafIdWAkUeGqGK0UuAOkaQv30njw3JXZfpRm7D7DCrENbRrmNQbwhn3WqdhtzwXQ4IuDsXxKcf201VbUhpDzukU9AITwdw8KmkBPv+zqSjLRiyKWdlbA8PlJuO3luR5RpDh4AmA4eoCA/hN7cWZBojYU71oy2m0SjPji1TtYKEmBABr25TIV0wdGtEz7D+IBnKw+BTtL0n+fpZiEl/hR8JbnswF7l0Wv+IasWPHdTqKxmkdAM4E+wShGknKtrkUBK2qmhfVpxLaPky14Tl1iseD8VkLCkIOeb/xYoVmztAXbMHd2aRwzuHX13uHugxNynxt5NynwgCCUCipvcAUGg5+BCpTYVWMH0t3RfWSQFQ3KKdXwva/B4cXZoXfgFdR1pmVW3DnqcNmM3+YtlF2pEGo94p06zznE723/7N50uCmUXvbFogf3AuIYjLx7AA2eEjp6thvL19Kr19J+xrpzV9DJfgiPWvQQl7fRLY01Q+YdYiDM9TobP+YAjub6jqGaCyRIPI+EMYzTHGZutakhffKWj9MjlousaHlll5Kwa7zASUtqtK3ZbxiBYcZsAJh31Bkkwr3FkHTRuZg03NvIsfDqmMDmZxxN3pZguZynM1UyfYL/8ohDkpHzXxObH5AS+0r5n3LI+7BbMla1gYVEk52rY=
    username: AgBA6gTiPY95BHODrd9t9gw/KGgiafOzM8y+lUgdsu94ONPYuM2tTB07MRPZ20pb+o6DFV9v1fD6Qi3rYsA/aGEM4H6Zg9ynHtZVk6xOwTrLzAK2wQz9VggbbCfQiX6ZoTNwg/z9h0sG45IwJkwR2fY9kwFsaAHsRZLfPVjHc7vAGvzI2K1KPgCDnLAgNc4oKWQ1Nh7miAxXvRhG98oQRdfx7i1MpD/77lFyw56xyxcQFXTmcAz8iJnHAYJ4l739oKIpIyqxOafBUFypgVfRh+0kR6xUuxBNZpbmoc19vGz7LFmCNTjR2EASsbYs+Zdqj5/HW4Nznr9Zsns4LF/sBDiYC3CxV8AkqWKAkI3mx0ibC5K4ceB3B1JD6GUXH48/bXAXx87QLdfWgr/xFBIycAzdOFHl+889hTrVSGNXVXqmoZw+cqWtg+IuNDsVYg9+m4XGyM3TkzpBz1zzJO5B2VklBBqy+BeHCKhkadU5WzcuGAGhiXCqwV/EQwU9THxKkYJ11w043xcTXHoZwUywkMEncw0kWJhdRCfyYIydlt75Rnk/MYXbp4IpGO9/Io99F9/pD8phzNkVzJnXBb5y8TkT45E2VwCrsNQE/TEVDLchlOZgEQOgD39yY5228GdR2tWKowIuFA60Pb0rVu+ArSFKb11WWWuwno3rVBCpiosTBUwdyKPxxqZ2so7duRCJ2w/2sfKfqg==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: db-secret
      namespace: default
