apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: db-secret
  namespace: portfolio
spec:
  encryptedData:
    password: AgB/RRnemQmlmfteN1lShDNeU13BGMznyqUL6S2nzjIeV5qj19tNFM+ojEu8SSIhxoaPuLfZGEAZ90ZORNHZBTw6z7klGjbPbG3ekBgFWJcWDZN7/k4WgyUwcaLVSqtagjYI3cWtO9UGbHMv9D7cVRE76qqG5nTMAyXmmnkE1gutruaPp+sYm/EhSumCWogmXAF5rHkGKQVLpti56qgO8gb53aOoavuey22+2ecZFAdOjnvoFINohkXdi9g6M0JiNUVrfSPscaXVNWZm2r4nv0/5CqSOLCxln4oiHe5zzaGUtHMchZq03F2xfrQYAYQUqjy6yXssBOzxBE/ReaedpAs0waddlCgLmud6weHLEuoh/9zpw0nDtWwXs2tBqwpEv1Dg/LAUOdn4CXEAkp3XmpwV1qS/FasTr4x6CaWRT9oenb+yeEI/XPPkAkgKO4mpsPHDeocR7sKF/Jko1qXo/bqjVSKvunVsHgKb1NIq6jvZu8MBJmrrPHGp+SAcgLsRvQGszfdpkW2pm6N7CyaCFbJPSjGeWV1U8Em8bh/Cf4+e2Do+Q8pYXUnW5nIL4+nwoFKInkULDOdepHgnT0LKfKA7BQUskGY5YonhLrmbCw0o8y1o3i6FH4g1MsWWhdafZGHexiW6LIY5+tVVjlK0i3MbYPZpxCyVfrAomD2H5MaKNqGhabTvt+gUYBLsXUKaRpRyMlUkKZZ263w=
    username: AgBxAIGbRCLZAxdpkT4AKKKu2HMIOvVraX6rnnLRlQXT2LJfgIw/8NecqbPDZzItMWrVx8AGgUponHimq9BGzTXgMOihk7syoYLoMdanlLqNxriaSuK04LwcBFuvW+vkYH8Ux9qYRt7CjXcmIv1x2FfMw/rgy0Tnq+XsBqfB8UsGfkUZ5gMPFjEO8uguuVQBAij0TVNGLXOvgchQs2FqE8JmR6HYxAw+jHZM9yt2mo9Go1h19G3xU+oj6SOEnKuN7TGk2Wu4ImeughdFVWey8voAm7829uH9oPjBxCVba3SYrpTYY3yslz1MdnSvzvqwjY+Fun1S1dQYHRE5Ce4y3433YkF8LBqAb8P6fKFRw4+ZtfhvOgWnC4E3DyaIbs6bdlBijaT61cQycinlYvQLccLfcvfiMGb8cgKUKAD8scArRWRZtjGMNJBAZTiveKy/WgqtodrmmSBKHN9dh+/KF7jL7bdpaldQCYqvydV8jxKPSQAKEnpfC8qoiWQBO/MglaYFAn7XbLS/Mv8U92MbH6Blt6wB6p5JLIg5TuI0cDRfxJNLUTvSwQwxBIaSO814NVaf60OsMdOpfc9fJqyB/8WyqOanv+vI4l03kLuWln2BI+118Iqr89LrVJrkO749aNT7AydpBrrdSrEAwzVQfe051pjQmRtoSSy1IMMKlBiiz4wTEi0rAt9o9SGvgao5UXB7UGDnZg==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: db-secret
      namespace: portfolio
